version: "3"

services:
  bot:
    build: .
    volumes:
      - .:/app
    container_name: bot
    command: bash -c "while true; do python main.py; sleep 300; done"
    env_file:
      - bot.env
    networks:
      - bot_network
      - studify
networks:
  bot_network:
    external: true
  studify:
    external: true

